export default {
  changeBannerSite(state,site){
    state.bannerSite=site;
  },
  increment (state, value) {
    state.platformCategory =value;
  },
  increTime(state,value){
    state.time=value;
  },
  changeKeyword(state,value){
    state.keyword=value;
  },
  changeCondition(state,arr){
    state.selectConditions.splice(0,state.selectConditions.length);
    arr.forEach((item)=>{
      state.selectConditions.push(item);
    })
  },
  selectKeyword(state,arr){
    state.selectKeywords.splice(0,state.selectKeywords.length);
    arr.forEach((item)=>{
      state.selectKeywords.push(item);
    })
  },
  changeState(state,value){
    state.addKeywordState=value;
  },
  deleleKeyword(state,keyword){
    state.selectKeywords.forEach((obj,i)=>{
      if(obj.keywords==keyword){
        state.selectKeywords.splice(i,1);
      }
    })
  },
  changeSite(state,site){
    state.siteType=site;
  },
  setSites(state,site){
    state.sites=site;
  },
  changeA9TotalCount(state,count){
    state.A9totalCount=count;
  },
  /***********DI************/
  //改变类目
  changeCategory(state,category){
    state.category=category;
  },
  //改变榜单
  changescgsTags(state,scgsTags){
    state.scgsTags=scgsTags;
  },
  //改变bsr品类
  changeBsr(state,bsr){
    state.bsr=bsr;
  },
  changeNoMoreData(state,flag){
    state.noMoreData=flag;
  },
  //改变类目数据数组
  changeCategoryArray(state,categoryArray){
    state.categoryArray=categoryArray;
  },
  //改变表格按钮切换
  chanegTabSelect(state,tabname){
    state.selectTab=tabname;
  },
  changeIsReadTotal(state,flag){
    state.isReadTotal=flag;
  },
  //品牌数量
  changeBrandCount(state,brandCount){
    state.brandCount=brandCount;
  },
  //评论总数
  changeCommentCount(state,commentCount){
    state.commentCount=commentCount;
  },
  //显示产品详情
  isShowAsin(state,showAsin){
    state.isShowAsin=showAsin;
  },
  changeAsinPramas(state,asin){
    state.asinParmas=asin;
  },
  changeDISitetype(state,site){
    state.site=site;
  },
  getebayisCollect(state,ebayisCollect){
    state.ebayisCollect=ebayisCollect;
  },
  getcondition(state,condition){
    state.condition=condition;
  },
  changeDevelopStatus(state,developStatus){
    state.developStatus=developStatus;
  },
  changeCategoryState(state,value){
    state.categorySearch=value;
  },
  /*ebay*/
  changeEbaySite(state,site){
    state.ebaySite=site;
  },
  changeEbayCategory(state,category){
    state.ebaycategory=category;
  },
  changeMoniorBtn(state,id){
    state.monitorCompetitiveBtn=id;
  },
  changeEbaySellerCategory(state,category){
    state.ebaysellerCategory=category;
  },
  /*****aliExpress********/
  changeAliExpressCategory(state,category){
    state.aliExpressCategory=category;
  },
  changeAliExpressBtn(state,btn){
    state.btnId=btn;
  },
  changeAliExpressTab(state,tab){
    state.tabId=tab;
  },
  chanegAliExpressRankType(state,rank){
    state.rankType=rank;
  },
  /*****铺货********/
  getDistridition(state,val){
    state.isDistribution=val;
  },
  /*****关联参数********/
  getfromTable(state,val){
    state.fromTable=val;
  },
  getSupplyNum(state,val){
    state.supplierId=val;
  },
  getPuhupParams(state,val){
    state.puhuoParams=val;
  },
  getEmaTag(state,val){
    state.emaTag=val;
  },
  getpuhuourl(state,val){
    state.puhuourl=val;
  },
  initTableState(state,val){
    state.initTable=val;
  },
  getShowpuhuo(state,val){
    state.showPuhuo=val;
  },
  changePuhuoPath(state,val){
    state.puhuoPath=val;
  },
  changeBaoguanState(state,val){
    state.isBaoguan=val;
  },
  changeTableScroll(state, val) {
    state.tableScroll = val
  },
  getUserName(state,val){
    state.userName = val
  },
  getUserInfo(state,val){
    state.userInfo = val
  },
  changeTaskId(state,val){
    state.taskId=val;
  }
}
